### ISSUE TITLE
部署后，通过action secrets设置的变量 MONGODB_URI 为undefined

### ISSUE THREAD

**Issue by SojinEvo** [SojinEvo/ChatAi#1]
部署项目中process.env.MONGODB_URI 连接数据库，一直为undefined，此变量通过action secrets设置

**Comment by SojinEvo** [comment]
但在Vercel中设置的变量并部署后，可以成功

**Comment by SojinEvo** [comment]
报错如下：报错：Run npx --no-install next build
⚠ No build cache found. Please configure build caching for faster rebuilds. Read more: https://nextjs.org/docs/messages/no-cache
Attention: Next.js now collects completely anonymous telemetry regarding usage.
This information is used to shape Next.js' roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://nextjs.org/telemetry

▲ Next.js 14.2.4

Creating an optimized production build ...
✓ Compiled successfully
Linting and checking validity of types ...
Collecting page data ...
Connecting to MongoDB... undefined
Error: Please add your Mongo URI to .env.local
at 2[6](https://github.com/SojinEvo/ChatAi/actions/runs/10386210903/job/28757044159#step:8:7)039 (/home/runner/work/ChatAi/ChatAi/.next/server/app/api/getAiKeys/route.js:1:1615)
at t (/home/runner/work/ChatAi/ChatAi/.next/server/webpack-runtime.js:1:128)
at 29408 (/home/runner/work/ChatAi/ChatAi/.next/server/app/api/getAiKeys/route.js:1:492)
at t (/home/runner/work/ChatAi/ChatAi/.next/server/webpack-runtime.js:1:128)
at o (/home/runner/work/ChatAi/ChatAi/.next/server/app/api/getAiKeys/route.js:1:1[7](https://github.com/SojinEvo/ChatAi/actions/runs/10386210903/job/28757044159#step:8:8)64)
at /home/runner/work/ChatAi/ChatAi/.next/server/app/api/getAiKeys/route.js:1:1795
at t.X (/home/runner/work/ChatAi/ChatAi/.next/server/webpack-runtime.js:1:1206)
at /home/runner/work/ChatAi/ChatAi/.next/server/app/api/getAiKeys/route.js:1:1777
at Object. (/home/runner/work/ChatAi/ChatAi/.next/server/app/api/getAiKeys/route.js:1:1[8](https://github.com/SojinEvo/ChatAi/actions/runs/10386210903/job/28757044159#step:8:9)23)
at Module._compile (node:internal/modules/cjs/loader:1358:14)

Build error occurred
Error: Failed to collect page data for /api/getAiKeys
at /home/runner/work/ChatAi/ChatAi/node_modules/next/dist/build/utils.js:1268:15
at process.processTicksAndRejections (node:internal/process/task_queues:[9](https://github.com/SojinEvo/ChatAi/actions/runs/10386210903/job/28757044159#step:8:10)5:5) {
type: 'Error'
}
Error: Process completed with exit code 1.
